version: "3.8"

services:
  devcontainer:
    command: sleep infinity
    image: johnnyhuy/versioneer/devcontainer:dev
    working_dir: /workspaces/versioneer
    volumes:
      - ~/.ssh/:/home/node/.ssh:cached
      - ~/.gnupg/:/home/node/.gnupg:cached
      - ./:/workspaces/versioneer:cached
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  versioneer:
    image: johnnyhuy/versioneer:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
