version: "3.8"

services:
  devcontainer:
    command: sleep infinity
    image: johnnyhuy/versioneer/devcontainer:dev
    volumes:
      - ~/.ssh/:/home/vscode/.ssh:cached
      - ~/.gnupg/:/home/vscode/.gnupg:cached
      - ./:/workspaces/versioneer:cached
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
