name: Run tests

on:
  push:
    branches: '*'

jobs:
  test:

    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
    - name: Cancel Previous Runs
      uses: n1hility/cancel-previous-runs@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        docker-compose pull
        docker-compose build devcontainer
        docker-compose run --rm devcontainer npm ci
        docker-compose run --rm devcontainer npm test -
