name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
    - name: Cancel Previous Runs
      uses: n1hility/cancel-previous-runs@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker-compose pull
        docker-compose build devcontainer
    
    - name: Test
      run: docker-compose run devcontainer npm test -
