name: Version

on:
  push:
    branches:
      - master

jobs:
  test:

    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
    - name: Cancel Previous Runs
      uses: n1hility/cancel-previous-runs@v2
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        docker compose build versioneer
        docker compose run -T --rm versioneer apply
        git push --follow-tags
